import type { Oferta } from '../types/oferta'

// Dane tymczasowe — do podmiany na prawdziwe API (docs/api/) po jego publikacji.
// Struktura zgodna z kontraktem Oferta 0.1.0 (packages/core/models.py).
// Zawiera świadomie przypadki brzegowe: brak ceny, brak terminu, cena "od".

const teraz = () => new Date().toISOString()

export const OFERTY_MOCK: Oferta[] = [
  {
    id: 'ustron-rownica-1',
    adapter: 'demo',
    zrodlo_id: 'pakiet-relaks-7dni',
    osrodek_klucz: 'uzdrowisko-ustron-rownica',
    osrodek_nazwa: 'Uzdrowisko Ustroń — Sanatorium Równica',
    miejscowosc: 'Ustroń',
    wojewodztwo: 'śląskie',
    nip: '5480000000',
    nazwa_pakietu: 'Pobyt lecznico-wypoczynkowy 7 dni',
    liczba_dni: 7,
    liczba_nocy: 6,
    termin_od: '2026-10-05',
    termin_do: '2026-10-12',
    dostepny: true,
    cena: '2450.00',
    jednostka_ceny: 'turnus_osoba',
    waluta: 'PLN',
    cena_od: true,
    wyzywienie: 'fb',
    typ_pokoju: 'dwuosobowy',
    doplata_jedynka: '350.00',
    liczba_zabiegow_dziennie: 3,
    zabiegi: ['Kąpiel borowinowa', 'Masaż suchy', 'Inhalacje', 'Krioterapia'],
    opieka_lekarska: true,
    oplata_klimatyczna_doba: '2.50',
    profile: ['ortopedyczno_urazowy', 'reumatologiczny'],
    udogodnienia: {
      winda: true,
      dostepny_dla_wozka: true,
      parking: true,
      parking_platny: false,
      wifi: true,
      basen: true,
      zwierzeta: false,
      odleglosc_od_centrum_m: 800,
    },
    telefon: '+48 33 854 00 00',
    url_rezerwacji: 'https://uzdrowisko-ustron.pl/rezerwacja/rownica-relaks',
    zrodlo: {
      url: 'https://uzdrowisko-ustron.pl/oferta/pakiet-relaks-7dni',
      pobrano_o: teraz(),
      adapter: 'demo',
      wersja_adaptera: '0.1.0',
      hash_tresci: 'a1b2c3',
    },
  },
  {
    id: 'ustron-rownica-2',
    adapter: 'demo',
    zrodlo_id: 'pakiet-kardio-14dni',
    osrodek_klucz: 'uzdrowisko-ustron-rownica',
    osrodek_nazwa: 'Uzdrowisko Ustroń — Sanatorium Równica',
    miejscowosc: 'Ustroń',
    wojewodztwo: 'śląskie',
    nip: '5480000000',
    nazwa_pakietu: 'Turnus kardiologiczny 14 dni',
    liczba_dni: 14,
    liczba_nocy: 13,
    termin_od: '2026-11-02',
    termin_do: '2026-11-16',
    dostepny: true,
    cena: '4200.00',
    jednostka_ceny: 'turnus_osoba',
    waluta: 'PLN',
    cena_od: false,
    wyzywienie: 'fb',
    typ_pokoju: 'jednoosobowy',
    doplata_jedynka: null,
    liczba_zabiegow_dziennie: 4,
    zabiegi: ['Kinezyterapia', 'Elektroterapia', 'Gimnastyka w basenie'],
    opieka_lekarska: true,
    oplata_klimatyczna_doba: '2.50',
    profile: ['kardiologiczny', 'naczyn_obwodowych'],
    udogodnienia: {
      winda: true,
      dostepny_dla_wozka: true,
      parking: true,
      parking_platny: false,
      wifi: true,
      basen: true,
      zwierzeta: false,
      odleglosc_od_centrum_m: 800,
    },
    telefon: '+48 33 854 00 00',
    url_rezerwacji: 'https://uzdrowisko-ustron.pl/rezerwacja/rownica-kardio',
    zrodlo: {
      url: 'https://uzdrowisko-ustron.pl/oferta/pakiet-kardio-14dni',
      pobrano_o: teraz(),
      adapter: 'demo',
      wersja_adaptera: '0.1.0',
      hash_tresci: 'd4e5f6',
    },
  },
  {
    id: 'kolobrzeg-perla-1',
    adapter: 'demo',
    zrodlo_id: 'oferta-jesien-2026',
    osrodek_klucz: 'sanatorium-perla-baltyku-kolobrzeg',
    osrodek_nazwa: 'Sanatorium Perła Bałtyku',
    miejscowosc: 'Kołobrzeg',
    wojewodztwo: 'zachodniopomorskie',
    nip: null,
    nazwa_pakietu: 'Jesienna kuracja nadmorska',
    liczba_dni: 10,
    liczba_nocy: 9,
    termin_od: '2026-10-15',
    termin_do: '2026-10-25',
    dostepny: null,
    cena: '1890.00',
    jednostka_ceny: 'osobodoba',
    waluta: 'PLN',
    cena_od: true,
    wyzywienie: 'hb',
    typ_pokoju: 'dwuosobowy',
    doplata_jedynka: '80.00',
    liczba_zabiegow_dziennie: 2,
    zabiegi: ['Inhalacje solankowe', 'Aerozoloterapia', 'Masaż klasyczny'],
    opieka_lekarska: null,
    oplata_klimatyczna_doba: '2.60',
    profile: ['gorne_drogi_oddechowe', 'dolne_drogi_oddechowe'],
    udogodnienia: {
      winda: true,
      dostepny_dla_wozka: null,
      parking: true,
      parking_platny: true,
      wifi: true,
      basen: false,
      zwierzeta: true,
      odleglosc_od_centrum_m: 400,
    },
    telefon: '+48 94 352 00 00',
    url_rezerwacji: null,
    zrodlo: {
      url: 'https://perlabaltyku.pl/oferta/jesien-2026',
      pobrano_o: teraz(),
      adapter: 'demo',
      wersja_adaptera: '0.1.0',
      hash_tresci: 'g7h8i9',
    },
  },
  {
    id: 'kolobrzeg-perla-2',
    adapter: 'demo',
    zrodlo_id: 'oferta-cukrzyca-2026',
    osrodek_klucz: 'sanatorium-perla-baltyku-kolobrzeg',
    osrodek_nazwa: 'Sanatorium Perła Bałtyku',
    miejscowosc: 'Kołobrzeg',
    wojewodztwo: 'zachodniopomorskie',
    nip: null,
    nazwa_pakietu: 'Program dla diabetyków',
    liczba_dni: 14,
    liczba_nocy: 13,
    termin_od: null,
    termin_do: null,
    dostepny: null,
    cena: null,
    jednostka_ceny: null,
    waluta: 'PLN',
    cena_od: false,
    wyzywienie: 'fb',
    typ_pokoju: null,
    doplata_jedynka: null,
    liczba_zabiegow_dziennie: null,
    zabiegi: ['Konsultacja diabetologiczna', 'Zajęcia dietetyczne'],
    opieka_lekarska: true,
    oplata_klimatyczna_doba: null,
    profile: ['cukrzyca', 'endokrynologiczny'],
    udogodnienia: {
      winda: true,
      dostepny_dla_wozka: null,
      parking: true,
      parking_platny: true,
      wifi: true,
      basen: false,
      zwierzeta: true,
      odleglosc_od_centrum_m: 400,
    },
    telefon: '+48 94 352 00 00',
    url_rezerwacji: null,
    zrodlo: {
      url: 'https://perlabaltyku.pl/oferta/cukrzyca-2026',
      pobrano_o: teraz(),
      adapter: 'demo',
      wersja_adaptera: '0.1.0',
      hash_tresci: 'j1k2l3',
    },
  },
  {
    id: 'krynica-zdroj-1',
    adapter: 'demo',
    zrodlo_id: 'oferta-relaks-podstawowy',
    osrodek_klucz: 'sanatorium-krynica-zdroj-nowy-dom',
    osrodek_nazwa: 'Sanatorium „Nowy Dom Zdrojowy” Krynica-Zdrój',
    miejscowosc: 'Krynica-Zdrój',
    wojewodztwo: 'małopolskie',
    nip: '7340000000',
    nazwa_pakietu: 'Pobyt relaksacyjny w górach',
    liczba_dni: 8,
    liczba_nocy: 7,
    termin_od: '2026-09-28',
    termin_do: '2026-10-05',
    dostepny: false,
    cena: '2100.00',
    jednostka_ceny: 'turnus_osoba',
    waluta: 'PLN',
    cena_od: false,
    wyzywienie: 'sniadania',
    typ_pokoju: 'studio',
    doplata_jedynka: '200.00',
    liczba_zabiegow_dziennie: 1,
    zabiegi: ['Kąpiel mineralna', 'Sauna'],
    opieka_lekarska: false,
    oplata_klimatyczna_doba: '2.40',
    profile: ['uklad_trawienia', 'nieznany'],
    udogodnienia: {
      winda: false,
      dostepny_dla_wozka: false,
      parking: true,
      parking_platny: false,
      wifi: true,
      basen: false,
      zwierzeta: false,
      odleglosc_od_centrum_m: 1200,
    },
    telefon: '+48 18 471 00 00',
    url_rezerwacji: 'https://nowydomzdrojowy.pl/rezerwacja',
    zrodlo: {
      url: 'https://nowydomzdrojowy.pl/oferta/relaks-podstawowy',
      pobrano_o: teraz(),
      adapter: 'demo',
      wersja_adaptera: '0.1.0',
      hash_tresci: 'm4n5o6',
    },
  },
  {
    id: 'krynica-zdroj-2',
    adapter: 'demo',
    zrodlo_id: 'oferta-osteoporoza',
    osrodek_klucz: 'sanatorium-krynica-zdroj-nowy-dom',
    osrodek_nazwa: 'Sanatorium „Nowy Dom Zdrojowy” Krynica-Zdrój',
    miejscowosc: 'Krynica-Zdrój',
    wojewodztwo: 'małopolskie',
    nip: '7340000000',
    nazwa_pakietu: 'Program profilaktyki osteoporozy',
    liczba_dni: 10,
    liczba_nocy: 9,
    termin_od: '2026-11-10',
    termin_do: '2026-11-19',
    dostepny: true,
    cena: '2650.00',
    jednostka_ceny: 'turnus_osoba',
    waluta: 'PLN',
    cena_od: true,
    wyzywienie: 'hb',
    typ_pokoju: 'dwuosobowy',
    doplata_jedynka: '250.00',
    liczba_zabiegow_dziennie: 2,
    zabiegi: ['Densytometria', 'Gimnastyka lecznicza', 'Kąpiel mineralna'],
    opieka_lekarska: true,
    oplata_klimatyczna_doba: '2.40',
    profile: ['osteoporoza'],
    udogodnienia: {
      winda: false,
      dostepny_dla_wozka: false,
      parking: true,
      parking_platny: false,
      wifi: true,
      basen: false,
      zwierzeta: false,
      odleglosc_od_centrum_m: 1200,
    },
    telefon: '+48 18 471 00 00',
    url_rezerwacji: 'https://nowydomzdrojowy.pl/rezerwacja',
    zrodlo: {
      url: 'https://nowydomzdrojowy.pl/oferta/osteoporoza',
      pobrano_o: teraz(),
      adapter: 'demo',
      wersja_adaptera: '0.1.0',
      hash_tresci: 'p7q8r9',
    },
  },
]
