import type { Oferta } from '../types/oferta'

// Dane tymczasowe zgodne z realnym kontraktem z docs/api/specyfikacja.md
// (branch backend/mvp-api-storage). Do podmiany na prawdziwe API po wdrożeniu
// backendu — patrz src/api/index.ts. Zawiera świadomie przypadki brzegowe:
// brak ceny/terminu, cena "od", szacowany_koszt_calkowity=null gdy nie da się
// go jednoznacznie policzyć.

const teraz = () => new Date().toISOString()

export const OFERTY_MOCK: Oferta[] = [
  {
    id: 1,
    adapter: 'demo',
    zrodlo_id: 'pakiet-relaks-7dni',
    osrodek: {
      klucz: 'uzdrowisko-ustron-rownica',
      nazwa: 'Uzdrowisko Ustroń — Sanatorium Równica',
      miejscowosc: 'Ustroń',
      wojewodztwo: 'śląskie',
      nip: '5480000000',
      telefon: '+48 33 854 00 00',
    },
    pakiet: {
      nazwa: 'Pobyt lecznico-wypoczynkowy 7 dni',
      liczba_dni: 7,
      liczba_nocy: 6,
      termin_od: '2026-10-05',
      termin_do: '2026-10-12',
      dostepny: true,
    },
    cena: {
      wartosc: '2450.00',
      waluta: 'PLN',
      jednostka: 'turnus_osoba',
      cena_od: true,
      szacowany_koszt_calkowity: '2450.00',
      doplata_jedynka: '350.00',
      oplata_klimatyczna_doba: '2.50',
    },
    standard: {
      wyzywienie: 'fb',
      typ_pokoju: 'dwuosobowy',
      liczba_zabiegow_dziennie: 3,
      zabiegi: ['Kąpiel borowinowa', 'Masaż suchy', 'Inhalacje', 'Krioterapia'],
      opieka_lekarska: true,
    },
    profile: ['ortopedyczno_urazowy', 'reumatologiczny'],
    udogodnienia: {
      winda: true,
      dostepny_dla_wozka: true,
      parking: true,
      parking_platny: false,
      wifi: true,
      basen: true,
      zwierzeta: false,
      odleglosc_od_centrum_m: 800,
    },
    linki: {
      url_rezerwacji: 'https://uzdrowisko-ustron.pl/rezerwacja/rownica-relaks',
      url_zrodla: 'https://uzdrowisko-ustron.pl/oferta/pakiet-relaks-7dni',
      pobrano_o: teraz(),
    },
  },
  {
    id: 2,
    adapter: 'demo',
    zrodlo_id: 'pakiet-kardio-14dni',
    osrodek: {
      klucz: 'uzdrowisko-ustron-rownica',
      nazwa: 'Uzdrowisko Ustroń — Sanatorium Równica',
      miejscowosc: 'Ustroń',
      wojewodztwo: 'śląskie',
      nip: '5480000000',
      telefon: '+48 33 854 00 00',
    },
    pakiet: {
      nazwa: 'Turnus kardiologiczny 14 dni',
      liczba_dni: 14,
      liczba_nocy: 13,
      termin_od: '2026-11-02',
      termin_do: '2026-11-16',
      dostepny: true,
    },
    cena: {
      wartosc: '4200.00',
      waluta: 'PLN',
      jednostka: 'turnus_osoba',
      cena_od: false,
      szacowany_koszt_calkowity: '4200.00',
      doplata_jedynka: null,
      oplata_klimatyczna_doba: '2.50',
    },
    standard: {
      wyzywienie: 'fb',
      typ_pokoju: 'jednoosobowy',
      liczba_zabiegow_dziennie: 4,
      zabiegi: ['Kinezyterapia', 'Elektroterapia', 'Gimnastyka w basenie'],
      opieka_lekarska: true,
    },
    profile: ['kardiologiczny', 'naczyn_obwodowych'],
    udogodnienia: {
      winda: true,
      dostepny_dla_wozka: true,
      parking: true,
      parking_platny: false,
      wifi: true,
      basen: true,
      zwierzeta: false,
      odleglosc_od_centrum_m: 800,
    },
    linki: {
      url_rezerwacji: 'https://uzdrowisko-ustron.pl/rezerwacja/rownica-kardio',
      url_zrodla: 'https://uzdrowisko-ustron.pl/oferta/pakiet-kardio-14dni',
      pobrano_o: teraz(),
    },
  },
  {
    id: 3,
    adapter: 'demo',
    zrodlo_id: 'oferta-jesien-2026',
    osrodek: {
      klucz: 'sanatorium-perla-baltyku-kolobrzeg',
      nazwa: 'Sanatorium Perła Bałtyku',
      miejscowosc: 'Kołobrzeg',
      wojewodztwo: 'zachodniopomorskie',
      nip: null,
      telefon: '+48 94 352 00 00',
    },
    pakiet: {
      nazwa: 'Jesienna kuracja nadmorska',
      liczba_dni: 10,
      liczba_nocy: 9,
      termin_od: '2026-10-15',
      termin_do: '2026-10-25',
      dostepny: null,
    },
    cena: {
      wartosc: '1890.00',
      waluta: 'PLN',
      jednostka: 'osobodoba',
      cena_od: true,
      szacowany_koszt_calkowity: '18900.00',
      doplata_jedynka: '80.00',
      oplata_klimatyczna_doba: '2.60',
    },
    standard: {
      wyzywienie: 'hb',
      typ_pokoju: 'dwuosobowy',
      liczba_zabiegow_dziennie: 2,
      zabiegi: ['Inhalacje solankowe', 'Aerozoloterapia', 'Masaż klasyczny'],
      opieka_lekarska: null,
    },
    profile: ['gorne_drogi_oddechowe', 'dolne_drogi_oddechowe'],
    udogodnienia: {
      winda: true,
      dostepny_dla_wozka: null,
      parking: true,
      parking_platny: true,
      wifi: true,
      basen: false,
      zwierzeta: true,
      odleglosc_od_centrum_m: 400,
    },
    linki: {
      url_rezerwacji: null,
      url_zrodla: 'https://perlabaltyku.pl/oferta/jesien-2026',
      pobrano_o: teraz(),
    },
  },
  {
    id: 4,
    adapter: 'demo',
    zrodlo_id: 'oferta-cukrzyca-2026',
    osrodek: {
      klucz: 'sanatorium-perla-baltyku-kolobrzeg',
      nazwa: 'Sanatorium Perła Bałtyku',
      miejscowosc: 'Kołobrzeg',
      wojewodztwo: 'zachodniopomorskie',
      nip: null,
      telefon: '+48 94 352 00 00',
    },
    pakiet: {
      nazwa: 'Program dla diabetyków',
      liczba_dni: 14,
      liczba_nocy: 13,
      termin_od: null,
      termin_do: null,
      dostepny: null,
    },
    cena: {
      wartosc: null,
      waluta: 'PLN',
      jednostka: null,
      cena_od: false,
      szacowany_koszt_calkowity: null,
      doplata_jedynka: null,
      oplata_klimatyczna_doba: null,
    },
    standard: {
      wyzywienie: 'fb',
      typ_pokoju: null,
      liczba_zabiegow_dziennie: null,
      zabiegi: ['Konsultacja diabetologiczna', 'Zajęcia dietetyczne'],
      opieka_lekarska: true,
    },
    profile: ['cukrzyca', 'endokrynologiczny'],
    udogodnienia: {
      winda: true,
      dostepny_dla_wozka: null,
      parking: true,
      parking_platny: true,
      wifi: true,
      basen: false,
      zwierzeta: true,
      odleglosc_od_centrum_m: 400,
    },
    linki: {
      url_rezerwacji: null,
      url_zrodla: 'https://perlabaltyku.pl/oferta/cukrzyca-2026',
      pobrano_o: teraz(),
    },
  },
  {
    id: 5,
    adapter: 'demo',
    zrodlo_id: 'oferta-relaks-podstawowy',
    osrodek: {
      klucz: 'sanatorium-krynica-zdroj-nowy-dom',
      nazwa: 'Sanatorium „Nowy Dom Zdrojowy” Krynica-Zdrój',
      miejscowosc: 'Krynica-Zdrój',
      wojewodztwo: 'małopolskie',
      nip: '7340000000',
      telefon: '+48 18 471 00 00',
    },
    pakiet: {
      nazwa: 'Pobyt relaksacyjny w górach',
      liczba_dni: 8,
      liczba_nocy: 7,
      termin_od: '2026-09-28',
      termin_do: '2026-10-05',
      dostepny: false,
    },
    cena: {
      wartosc: '2100.00',
      waluta: 'PLN',
      jednostka: 'turnus_osoba',
      cena_od: false,
      szacowany_koszt_calkowity: '2100.00',
      doplata_jedynka: '200.00',
      oplata_klimatyczna_doba: '2.40',
    },
    standard: {
      wyzywienie: 'sniadania',
      typ_pokoju: 'studio',
      liczba_zabiegow_dziennie: 1,
      zabiegi: ['Kąpiel mineralna', 'Sauna'],
      opieka_lekarska: false,
    },
    profile: ['uklad_trawienia', 'nieznany'],
    udogodnienia: {
      winda: false,
      dostepny_dla_wozka: false,
      parking: true,
      parking_platny: false,
      wifi: true,
      basen: false,
      zwierzeta: false,
      odleglosc_od_centrum_m: 1200,
    },
    linki: {
      url_rezerwacji: 'https://nowydomzdrojowy.pl/rezerwacja',
      url_zrodla: 'https://nowydomzdrojowy.pl/oferta/relaks-podstawowy',
      pobrano_o: teraz(),
    },
  },
  {
    id: 6,
    adapter: 'demo',
    zrodlo_id: 'oferta-osteoporoza',
    osrodek: {
      klucz: 'sanatorium-krynica-zdroj-nowy-dom',
      nazwa: 'Sanatorium „Nowy Dom Zdrojowy” Krynica-Zdrój',
      miejscowosc: 'Krynica-Zdrój',
      wojewodztwo: 'małopolskie',
      nip: '7340000000',
      telefon: '+48 18 471 00 00',
    },
    pakiet: {
      nazwa: 'Program profilaktyki osteoporozy',
      liczba_dni: 10,
      liczba_nocy: 9,
      termin_od: '2026-11-10',
      termin_do: '2026-11-19',
      dostepny: true,
    },
    cena: {
      wartosc: '2650.00',
      waluta: 'PLN',
      jednostka: 'turnus_osoba',
      cena_od: true,
      szacowany_koszt_calkowity: '2650.00',
      doplata_jedynka: '250.00',
      oplata_klimatyczna_doba: '2.40',
    },
    standard: {
      wyzywienie: 'hb',
      typ_pokoju: 'dwuosobowy',
      liczba_zabiegow_dziennie: 2,
      zabiegi: ['Densytometria', 'Gimnastyka lecznicza', 'Kąpiel mineralna'],
      opieka_lekarska: true,
    },
    profile: ['osteoporoza'],
    udogodnienia: {
      winda: false,
      dostepny_dla_wozka: false,
      parking: true,
      parking_platny: false,
      wifi: true,
      basen: false,
      zwierzeta: false,
      odleglosc_od_centrum_m: 1200,
    },
    linki: {
      url_rezerwacji: 'https://nowydomzdrojowy.pl/rezerwacja',
      url_zrodla: 'https://nowydomzdrojowy.pl/oferta/osteoporoza',
      pobrano_o: teraz(),
    },
  },
]
